POST http://localhost:5000/api/wilders HTTP/1.1
content-type: application/json

{
    "name":"Lionel Delamare",
    "city": "Londres",
    "skills":[
        {"title":"english", "votes": 15},
        {"title":"mongo", "votes": 12}
    ]
}