POST http://localhost:5000/api/wilders HTTP/1.1
content-type: application/json

{
    "name":"H",
    "city": "Londres",
    "skills":[
        {"title":"e", "votes": -5},
        {"title":"mongo", "votes":"12UU"}
    ]
} 